/*
 * W4_contact_angle_150deg.java
 */

import com.comsol.model.*;
import com.comsol.model.util.*;

/** Model exported on Jun 20 2026, 05:44 by COMSOL 6.4.0.293. */
public class W4_contact_angle_150deg {

  public static Model run() {
    Model model = ModelUtil.create("Model");

    model
         .modelPath("D:\\_COMSOL_FILE_SAVE_\\COMSOL_Ring_Fountain\\06_true_moving_geometry_R3_ring_contactline_isolation\\04_wettedwall_contactline_controls\\models");

    model.label("R3_W4_contact_angle_150deg_20260620_022152");

    model.param().set("Rtank", "40[mm]");
    model.param().set("Zmin", "-30[mm]");
    model.param().set("Zmax", "30[mm]");
    model.param().set("Ro", "0.012[m]");
    model.param().set("Ri", "0.006[m]");
    model.param().set("h_ring", "0.002[m]");
    model.param().set("z_ring0", "-0.002[m]");
    model.param().set("z0", "0[mm]");
    model.param().set("eps_ls", "1[mm]");
    model.param().set("Vring", "0[m/s]");
    model.param().set("rho_w", "1000[kg/m^3]");
    model.param().set("mu_w", "1e-3[Pa*s]");
    model.param().set("rho_air", "1.2[kg/m^3]");
    model.param().set("mu_air", "1.8e-5[Pa*s]");
    model.param().set("sigma_wa", "0.072[N/m]");
    model.param().set("g0", "9.81[m/s^2]");
    model.param().set("t_end", "0.005[s]");
    model.param().set("dt", "1e-4[s]");

    model.component().create("comp1", true);

    model.component("comp1").geom().create("geom1", 2);
    model.component("comp1").geom("geom1").axisymmetric(true);
    model.component("comp1").geom("geom1").feature().create("tank", "Rectangle");
    model.component("comp1").geom("geom1").feature("tank").set("size", new String[]{"Rtank", "Zmax-Zmin"});
    model.component("comp1").geom("geom1").feature("tank").set("pos", new String[]{"0", "Zmin"});
    model.component("comp1").geom("geom1").feature().create("ring", "Rectangle");
    model.component("comp1").geom("geom1").feature("ring").set("size", new String[]{"Ro-Ri", "h_ring"});
    model.component("comp1").geom("geom1").feature("ring").set("pos", new String[]{"Ri", "z_ring0-h_ring/2"});
    model.component("comp1").geom("geom1").feature().create("dif1", "Difference");
    model.component("comp1").geom("geom1").feature("dif1").selection("input").set("tank");
    model.component("comp1").geom("geom1").feature("dif1").selection("input2").set("ring");
    model.component("comp1").geom("geom1").run();

    model.component("comp1").selection().create("sel_axis", "Box");
    model.component("comp1").selection("sel_axis").geom("geom1", 1);
    model.component("comp1").selection("sel_axis").set("entitydim", "1");
    model.component("comp1").selection("sel_axis").set("xmin", "-0.0002");
    model.component("comp1").selection("sel_axis").set("xmax", "0.0002");
    model.component("comp1").selection("sel_axis").set("ymin", "-0.0305");
    model.component("comp1").selection("sel_axis").set("ymax", "0.0305");
    model.component("comp1").selection("sel_axis").set("condition", "inside");
    model.component("comp1").selection().create("sel_top_open", "Box");
    model.component("comp1").selection("sel_top_open").geom("geom1", 1);
    model.component("comp1").selection("sel_top_open").set("entitydim", "1");
    model.component("comp1").selection("sel_top_open").set("xmin", "-0.0002");
    model.component("comp1").selection("sel_top_open").set("xmax", "0.0405");
    model.component("comp1").selection("sel_top_open").set("ymin", "0.0298");
    model.component("comp1").selection("sel_top_open").set("ymax", "0.030199999999999998");
    model.component("comp1").selection("sel_top_open").set("condition", "inside");
    model.component("comp1").selection().create("sel_bottom_wall", "Box");
    model.component("comp1").selection("sel_bottom_wall").geom("geom1", 1);
    model.component("comp1").selection("sel_bottom_wall").set("entitydim", "1");
    model.component("comp1").selection("sel_bottom_wall").set("xmin", "-0.0002");
    model.component("comp1").selection("sel_bottom_wall").set("xmax", "0.0405");
    model.component("comp1").selection("sel_bottom_wall").set("ymin", "-0.030199999999999998");
    model.component("comp1").selection("sel_bottom_wall").set("ymax", "-0.0298");
    model.component("comp1").selection("sel_bottom_wall").set("condition", "inside");
    model.component("comp1").selection().create("sel_outer_wall", "Box");
    model.component("comp1").selection("sel_outer_wall").geom("geom1", 1);
    model.component("comp1").selection("sel_outer_wall").set("entitydim", "1");
    model.component("comp1").selection("sel_outer_wall").set("xmin", "0.0398");
    model.component("comp1").selection("sel_outer_wall").set("xmax", "0.0402");
    model.component("comp1").selection("sel_outer_wall").set("ymin", "-0.0305");
    model.component("comp1").selection("sel_outer_wall").set("ymax", "0.0305");
    model.component("comp1").selection("sel_outer_wall").set("condition", "inside");
    model.component("comp1").selection().create("sel_ring_wall_inner", "Box");
    model.component("comp1").selection("sel_ring_wall_inner").geom("geom1", 1);
    model.component("comp1").selection("sel_ring_wall_inner").set("entitydim", "1");
    model.component("comp1").selection("sel_ring_wall_inner").set("xmin", "0.0058000000000000005");
    model.component("comp1").selection("sel_ring_wall_inner").set("xmax", "0.0062");
    model.component("comp1").selection("sel_ring_wall_inner").set("ymin", "-0.0032");
    model.component("comp1").selection("sel_ring_wall_inner").set("ymax", "-0.0008");
    model.component("comp1").selection("sel_ring_wall_inner").set("condition", "inside");
    model.component("comp1").selection().create("sel_ring_wall_outer", "Box");
    model.component("comp1").selection("sel_ring_wall_outer").geom("geom1", 1);
    model.component("comp1").selection("sel_ring_wall_outer").set("entitydim", "1");
    model.component("comp1").selection("sel_ring_wall_outer").set("xmin", "0.0118");
    model.component("comp1").selection("sel_ring_wall_outer").set("xmax", "0.0122");
    model.component("comp1").selection("sel_ring_wall_outer").set("ymin", "-0.0032");
    model.component("comp1").selection("sel_ring_wall_outer").set("ymax", "-0.0008");
    model.component("comp1").selection("sel_ring_wall_outer").set("condition", "inside");
    model.component("comp1").selection().create("sel_ring_wall_top", "Box");
    model.component("comp1").selection("sel_ring_wall_top").geom("geom1", 1);
    model.component("comp1").selection("sel_ring_wall_top").set("entitydim", "1");
    model.component("comp1").selection("sel_ring_wall_top").set("xmin", "0.0058000000000000005");
    model.component("comp1").selection("sel_ring_wall_top").set("xmax", "0.0122");
    model.component("comp1").selection("sel_ring_wall_top").set("ymin", "-0.0012000000000000001");
    model.component("comp1").selection("sel_ring_wall_top").set("ymax", "-0.0008");
    model.component("comp1").selection("sel_ring_wall_top").set("condition", "inside");
    model.component("comp1").selection().create("sel_ring_wall_bottom", "Box");
    model.component("comp1").selection("sel_ring_wall_bottom").geom("geom1", 1);
    model.component("comp1").selection("sel_ring_wall_bottom").set("entitydim", "1");
    model.component("comp1").selection("sel_ring_wall_bottom").set("xmin", "0.0058000000000000005");
    model.component("comp1").selection("sel_ring_wall_bottom").set("xmax", "0.0122");
    model.component("comp1").selection("sel_ring_wall_bottom").set("ymin", "-0.0032");
    model.component("comp1").selection("sel_ring_wall_bottom").set("ymax", "-0.0028");
    model.component("comp1").selection("sel_ring_wall_bottom").set("condition", "inside");
    model.component("comp1").selection().create("sel_ring_wall_confirmed", "Explicit");
    model.component("comp1").selection("sel_ring_wall_confirmed").geom("geom1", 1);
    model.component("comp1").selection("sel_ring_wall_confirmed").set(4, 5, 6, 7);

    model.component("comp1").mesh().create("mesh1");
    model.component("comp1").mesh("mesh1").autoMeshSize(5);
    model.component("comp1").mesh("mesh1").run();

    model.component("comp1").physics().create("spf", "LaminarFlow", "geom1");
    model.component("comp1").physics().create("ls", "LevelSet", "geom1");

    model.component("comp1").multiphysics().create("tpf1", "TwoPhaseFlowLevelSet", 2);
    model.component("comp1").multiphysics("tpf1").set("Fluid_physics", "spf");
    model.component("comp1").multiphysics("tpf1").set("Mathematics_physics", "ls");
    model.component("comp1").multiphysics("tpf1").selection().all();
    model.component("comp1").multiphysics("tpf1").set("rho1_mat", "userdef");
    model.component("comp1").multiphysics("tpf1").set("rho1", "rho_air");
    model.component("comp1").multiphysics("tpf1").set("mu1_mat", "userdef");
    model.component("comp1").multiphysics("tpf1").set("mu1", "mu_air");
    model.component("comp1").multiphysics("tpf1").set("rho2_mat", "userdef");
    model.component("comp1").multiphysics("tpf1").set("rho2", "rho_w");
    model.component("comp1").multiphysics("tpf1").set("mu2_mat", "userdef");
    model.component("comp1").multiphysics("tpf1").set("mu2", "mu_w");
    model.component("comp1").multiphysics("tpf1").set("IncludeSurfaceTension", true);
    model.component("comp1").multiphysics("tpf1").set("SurfaceTensionCoefficient", "userdef");
    model.component("comp1").multiphysics("tpf1").set("sigma", "sigma_wa");
    model.component("comp1").multiphysics().create("ww1", "WettedWall", 1);
    model.component("comp1").multiphysics("ww1").set("Fluid_physics", "spf");
    model.component("comp1").multiphysics("ww1").set("Mathematics_physics", "ls");
    model.component("comp1").multiphysics("ww1").selection().set(4, 5, 6, 7);
    model.component("comp1").multiphysics("ww1").set("BoundaryCondition", "NavierSlip");
    model.component("comp1").multiphysics("ww1").set("TranslationalVelocityOption", "Manual");
    model.component("comp1").multiphysics("ww1").set("utr", new String[]{"0", "-Vring", "0"});
    model.component("comp1").multiphysics("ww1").set("SpecifyContactAngle", "SpecifyContactAngleDirectly");
    model.component("comp1").multiphysics("ww1").set("thetaw", "5*pi/6");
    model.component("comp1").multiphysics("ww1").set("beta", "eps_ls");

    model.component("comp1").physics("spf").feature().create("out_top", "OutletBoundary", 1);
    model.component("comp1").physics("spf").feature("out_top").selection().set(3);
    model.component("comp1").physics("ls").feature().create("out_top", "Outlet", 1);
    model.component("comp1").physics("ls").feature("out_top").selection().set(3);
    model.component("comp1").physics("ls").feature("init1").set("phils_init", "flc2hs(z0-z,eps_ls)");
    model.component("comp1").physics("ls").feature("init1").set("phils", "flc2hs(z0-z,eps_ls)");
    model.component("comp1").physics("ls").feature("lsm1").set("epsilon_ls", "eps_ls");
    model.component("comp1").physics("ls").feature("lsm1").set("gamma", "0.01[m/s]");
    model.component("comp1").physics("spf").prop("PhysicalModelProperty").set("IncludeGravity", true);
    model.component("comp1").physics("spf").feature("grav1").set("g", new String[]{"0", "-g0", "0"});
    model.component("comp1").physics().create("ale", "MovingMesh", "geom1");
    model.component("comp1").physics("ale").create("free1", "FreeDeformation", 2);
    model.component("comp1").physics("ale").feature("free1").selection().all();
    model.component("comp1").physics("ale").create("move_ring", "PrescribedMeshDisplacement", 1);
    model.component("comp1").physics("ale").feature("move_ring").selection().set(4, 5, 6, 7);
    model.component("comp1").physics("ale").feature("move_ring").set("useDx", new String[]{"0", "1"});
    model.component("comp1").physics("ale").feature("move_ring").set("dx", new String[]{"0", "-Vring*t"});
    model.component("comp1").physics("ale").create("fix_outer", "PrescribedMeshDisplacement", 1);
    model.component("comp1").physics("ale").feature("fix_outer").selection().set(1, 2, 3, 8);
    model.component("comp1").physics("ale").feature("fix_outer").set("useDx", new String[]{"1", "1"});
    model.component("comp1").physics("ale").feature("fix_outer").set("dx", new String[]{"0", "0"});

    model.study().create("std1");
    model.study("std1").create("phasei", "PhaseInitialization");
    model.study("std1").feature("phasei").setSolveFor("/physics/spf", false);
    model.study("std1").create("time", "Transient");
    model.study("std1").feature("time").set("tlist", "range(0,dt,t_end)");
    model.study("std1").feature("time").set("initstudy", "std1");
    model.study("std1").feature("time").set("useinitsol", "on");
    model.study("std1").run();

    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "t");
    model.result().numerical("gev1").set("unit", "s");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical("gev1").computeResult();
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "r");
    model.result().numerical("gev1").set("unit", "m");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "r");
    model.result().numerical("eva1").set("unit", "m");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "z");
    model.result().numerical("gev1").set("unit", "m");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "z");
    model.result().numerical("eva1").set("unit", "m");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "phils");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "phils");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "reldetjacmin");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "reldetjacmin");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "reldetjac");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "reldetjac");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "qual");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical("gev1").computeResult();
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "dvol");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical("gev1").computeResult();
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "r");
    model.result().numerical("gev1").set("unit", "m");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "r");
    model.result().numerical("eva1").set("unit", "m");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "z");
    model.result().numerical("gev1").set("unit", "m");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "z");
    model.result().numerical("eva1").set("unit", "m");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical().remove("eva1");
    model.result().numerical().create("gev1", "EvalGlobal");
    model.result().numerical("gev1").set("expr", "Z");
    model.result().numerical("gev1").set("unit", "m");
    model.result().numerical("gev1").set("data", "dset1");
    model.result().numerical().remove("gev1");
    model.result().numerical().create("eva1", "Eval");
    model.result().numerical("eva1").set("expr", "Z");
    model.result().numerical("eva1").set("unit", "m");
    model.result().numerical("eva1").set("data", "dset1");
    model.result().numerical().remove("eva1");

    return model;
  }

  public static void main(String[] args) {
    run();
  }

}
